version: "3.08"

services:
  postgres:
    image: postgres:16-alpine
    container_name: bms-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: bankcards
      POSTGRES_USER: bankcards
      POSTGRES_PASSWORD: bankcards

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U bankcards -d bankcards"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: