server:
  # Default local port
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bankcards}
    username: ${DB_USER:bankcards}
    password: ${DB_PASSWORD:bankcards}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      open-in-view: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

security:
  jwt:
    # Override in production via environment variable
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION} # 1 hour

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG